#!/usr/bin/env ruby

if RUBY_VERSION < "3.2.0"
  warn "wotr requires Ruby 3.2.0 or newer (you have #{RUBY_VERSION})."
  warn "Install a newer Ruby: brew install ruby"
  exit 1
end

if ARGV.empty?
  require_relative '../lib/wotr/app'
  Wotr::App.run
else
  require_relative '../lib/wotr/version'
  require_relative '../lib/wotr/git'
  require_relative '../lib/wotr/repository'
  require_relative '../lib/wotr/worktree'
  require_relative '../lib/wotr/config'
  require_relative '../lib/wotr/cli'
  Wotr::CLI.run(ARGV)
end
